# Generated by Django 5.1.3 on 2024-11-17 09:22

from django.db import migrations

def add_roles(apps, schema_editor):
    Role = apps.get_model('api', 'Role')
    Role.objects.update_or_create(id=1, defaults={'role': 'user'})
    Role.objects.update_or_create(id=2, defaults={'role': 'admin'})

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_image_alter_passphrase_passphrase_and_more'),
    ]

    operations = [
        migrations.RunPython(add_roles),
    ]